Prepare for aarch64 in GCE
SUSE/mash pull request #830
Opened 2022-06-16 20:18 UTC by rjschwei

### What does this PR do? Why are we making this change?

Image creation for GCE images adds a new architecture setting to distinguish
  between x86_64 and aarch64. Set the image attribute on image creation.

### How will these changes be tested?

### How will this change be deployed? Any special considerations?

### Additional Information

We do not know the instance types yet as such invocation of img-proof will need another PR to handle testing.

2022-06-16 20:41 UTC, smarlowucf requested changes
Linting fails due to syntax error

2022-06-16 20:41 UTC, smarlowucf commented on mash/utils/gce.py
>          'rolloutOverride': rollout
Syntax error

2022-06-16 20:41 UTC, smarlowucf commented on mash/utils/gce.py
> +        'architecture': arch.upper()
This works in terms of Mash because we are injecting a driver that is set to alpha version. Given this code will be pulled into a utility I think it's okay to leave it. However, we may want keep in mind at least some error handling that directs a user what to do. E.g. if they inject a driver that is for version v1 and try to set architecture which doesn't not exist yet.

2022-06-22 13:35 UTC, smarlowucf commented
If we switch the test to use `aarch64` arch then it will hit the new loc and fix the coverage back to 100%.

2022-06-22 13:47 UTC, rjschwei commented
Sorry for the churn, cannot run the tests locally and am not in the moot to dig into it ATM. I'll get it sorted out eventually.

2022-06-22 19:38 UTC, merged